[Feature] 모집 게시글 하단 버튼
boostcampwm-2022/web13-moyeomoyeo pull request #93
Opened 2022-11-27 09:00 UTC by kong430

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 관련된 이슈와 연결 시켰나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역
스토리북에서 `ParticipantButton`을 확인해주세요.

- 클립보드 복사 위한 `useClipboard` hook 정의
- 안내 문구를 보여주기 위한 `AlertModal` 공통 컴포넌트 생성
- `ParticipantButton`과 하위 컴포넌트들 생성

## 문제 상황과 해결

- 작업 중 마주한 문제상황 및 해결방법을 남겨주세요.

## 비고

- 참고했던 링크 등 참고 사항을 적어주세요. 코드 리뷰하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.

2022-11-27 14:00 UTC, Yangseungchan requested changes

2022-11-27 14:00 UTC, Yangseungchan commented on frontend/src/components/common/AlertModal/AlertModal.stories.tsx
> +};
![modal 버그](https://user-images.githubusercontent.com/38908080/204139072-de2b4ce4-0c04-47dc-b9c2-30130b82587d.gif)

`AlertModal` 모달에 `onClose`를 선택적으로 받을 수 있게 해놔서 `AlertModal` Props로 `onClose`를 넘기지 않으면 에러가 발생하는 것 같습니다. 에러는 `onClose` 를 넘기지 않은 상태로 닫으려고하면 에러가 발생하는 것으로 보입니다. 아마 `@mantine/Modal` 에 `onClose` props로 undefined가 넘어가기 때문인것으로 보여요. 

이는 `ParticipantModal` 에서도 마찬가지 인 것 같습니다. 이번 PR에서 고치는 김에 같이 수정하는 것이 좋아보여요

2022-11-27 14:49 UTC, kong430 commented on frontend/src/components/common/AlertModal/AlertModal.stories.tsx
> +};
앗 모달 바깥영역을 클릭해 볼 생각은 못했네요. 확인 감사합니다!

2022-11-27 14:53 UTC, kong430 commented on frontend/src/components/common/AlertModal/index.tsx
> +};
toast를 만들어볼까 하다가 확인버튼이 있는 모달도 나쁘진 않을 것 같아서 만들었습니다!
신청 완료, 신청 취소 등등 유저의 요청이 정상적으로 처리 되었는지 단순히 알리는 목적으로 `AlertModal`을 사용하면 될 것 같아요 :)

2022-11-27 15:45 UTC, Yangseungchan approved these changes
AlertModal 과 ParticipantModal 의 수정을 고려해주시고 머지하시면 될것같습니다~ 수고하셨습니다!

2022-11-27 15:45 UTC, Yangseungchan commented on frontend/src/components/article/ParticipantsModal/ParticipantsModal.stories.tsx
> +  onClose: () => {},
onClose에 빈 함수를 넣는 방식을 선택하셨군요..!

2022-11-27 15:45 UTC, Yangseungchan commented on frontend/src/components/common/AlertModal/index.tsx
> +        <StyledModal opened={open} onClose={onClose} withCloseButton={false} centered>
여전히 `onClose` 를 선택적으로 받다보니 그자리에 사용자가 무심코 아무것도 안넣을 경우 여전히 `undefined`가 넘어갈 여지가 있을 것 같습니다. `onClose` 에 아무것도 안들어오면 그냥 빈 함수를 넘기도록 처리하는 건 어떨까요?

```tsx
 <StyledModal opened={open} onClose={onClose || (() => {})} ... />
```

2022-11-27 15:59 UTC, kong430 commented on frontend/src/components/common/AlertModal/index.tsx
> +        <StyledModal opened={open} onClose={onClose} withCloseButton={false} centered>
아 mantine Modal 자체가 `onClose`를 required로 받는군요..! 죄송합니다 제가 한눈을 팔고있었네요.
`ParticipantModal`과 `AlertModal`에서도 `onClose`를 required로 받게 수정하는 게 좋을 것 같습니다.

2022-11-28 04:36 UTC, pythonstrup approved these changes
고생하셨습니다.

2022-11-28 04:38 UTC, merged